// Flat ESLint config (ESLint 9 + typescript-eslint). This is the linter the codebase
// already anticipated via scattered `eslint-disable-next-line @typescript-eslint/*`
// directives. Scope: syntactic (non-type-checked) recommended rules — fast, no
// typed-linting program build. Type-aware rules are a deliberate follow-up.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import unusedImports from "eslint-plugin-unused-imports";
import globals from "globals";
import maxLinesRatchet from "./eslint-max-lines-ratchet.mjs";

// max-lines ratchet (audit F6): daemon.ts regrew 1558 → 1717 after its split
// because nothing guarded size. eslint-max-lines-ratchet.mjs (generated by
// scripts/generate-max-lines-ratchet.mjs) freezes EVERY src/**/*.ts file at its
// current line count, rounded up to the nearest 25 for breathing room.
//
// POLICY — numbers may only DECREASE. When you shrink a file, re-run the
// generator to lower its entry. Never raise an entry to let a file grow: that is
// the regression the ratchet exists to catch. A file that must genuinely grow
// needs a recorded justification in the PR, and even then the correct move is to
// SPLIT it (each piece < the 800-line house rule) rather than raise a ceiling.
// New files not in the table inherit the default 800 ceiling below.
const maxLinesRatchetOverrides = Object.entries(maxLinesRatchet).map(([file, max]) => ({
  files: [file],
  rules: { "max-lines": ["error", { max, skipBlankLines: false, skipComments: false }] }
}));

export default tseslint.config(
  {
    // Generated / vendored / build-output paths, plus the managed control-layer
    // hooks (.claude/** is not part of the TS build and is governed separately).
    ignores: ["node_modules/**", "coverage/**", "dist/**", "**/*.d.ts", ".claude/**"]
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Default max-lines ceiling for src/**/*.ts. The house rule is 800 (see
    // .claude/rules/typescript.md / coding-style). NEW files not yet in the
    // ratchet table inherit this; the per-file overrides (spread at the end of
    // this config) tighten each existing file to its frozen, lower ceiling.
    // Tests and scripts are intentionally NOT ratcheted.
    files: ["src/**/*.ts"],
    rules: {
      "max-lines": ["error", { max: 800, skipBlankLines: false, skipComments: false }]
    }
  },
  {
    // Type-aware rules apply only to src/** — that is what tsconfig includes (tests
    // and scripts are excluded), and it is the production surface where typed checks
    // (floating promises, unsafe any, etc.) matter most.
    files: ["src/**/*.ts"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: import.meta.dirname
      }
    },
    rules: {
      // The high-value type-aware rules (no-floating-promises, no-misused-promises,
      // await-thenable, ...) already pass clean and stay enforced. The rules below are
      // turned off as a documented baseline: they flag pre-existing `any`-flow debt
      // (pg rows, JSON.parse, external payloads) and intentional async-for-interface
      // signatures across a 49k-line codebase not written under typed linting. Burning
      // them down (real narrowing) is a separate hardening initiative; re-enable
      // incrementally as the `any` surface shrinks.
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-base-to-string": "off",
      "@typescript-eslint/restrict-template-expressions": "off",
      "@typescript-eslint/require-await": "off",
      // Auto-fixable in principle, but `--fix` produced tsc-breaking removals here
      // (no-unnecessary-type-assertion flagged load-bearing casts as redundant).
      // Disabled until the assertions can be reviewed case-by-case.
      "@typescript-eslint/no-unnecessary-type-assertion": "off",
      "@typescript-eslint/no-duplicate-type-constituents": "off"
    }
  },
  {
    // Forge import wall (CC-15): src/forge/** MUST NOT import from anything outside
    // src/forge/**, src/domain/**, zod, or node built-ins.
    //
    // Rationale: src/forge/ is shipped in the published package (files[] — P5-S1/CC-14).
    // Every import that escapes these four allowed zones would silently drag an unshipped
    // or service-coupled module into the consuming-repo install tree, breaking cross-repo
    // usage (X-1). Mirror style and rationale of the R2-C web-wall block above.
    //
    // The rule bans named forbidden zones (src/archon, src/core, src/admin, src/install,
    // src/mcp, src/runtime, src/store, src/evals, src/sql, src/grafana, web/**) rather
    // than trying to allowlist everything else, so new service modules cannot be silently
    // dragged in without a lint failure.
    //
    // Safe zones (not banned): node:*, zod, src/forge/**, src/domain/**.
    files: ["src/forge/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: [
                "**/src/archon/**", "../archon/**", "../../archon/**",
                "**/src/core/**", "../core/**", "../../core/**",
                "**/src/admin/**", "../admin/**", "../../admin/**",
                "**/src/install/**", "../install/**", "../../install/**",
                "**/src/mcp/**", "../mcp/**", "../../mcp/**",
                "**/src/runtime/**", "../runtime/**", "../../runtime/**",
                "**/src/store/**", "../store/**", "../../store/**",
                "**/src/evals/**", "../evals/**", "../../evals/**",
                "**/src/sql/**", "../sql/**", "../../sql/**",
                "**/src/grafana/**", "../grafana/**", "../../grafana/**",
                "**/web/**", "../web/**", "../../web/**",
              ],
              message:
                "src/forge/** must only import from src/forge/**, src/domain/**, zod, or node built-ins (CC-15). " +
                "Importing service-coupled or unshipped modules breaks consuming-repo cross-repo usage (X-1/R2-C).",
            },
          ],
        },
      ],
    },
  },
  {
    // Build scripts (.mjs) run in Node.js and use globals (console, process,
    // etc.) that are invisible to ESLint unless declared.  This block surfaces
    // them without disabling any other rules.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        ...globals.node,
      }
    }
  },
  {
    files: ["**/*.ts"],
    plugins: { "unused-imports": unusedImports },
    rules: {
      // TypeScript resolves identifier binding; core no-undef double-reports globals
      // (process, console, URL, ...) and is redundant with the compiler.
      "no-undef": "off",

      // Empty interfaces that extend a single supertype are a deliberate named
      // extension point in this codebase (e.g. ExecuteGapsCommandOptions); allow them.
      "@typescript-eslint/no-empty-object-type": ["error", { allowInterfaces: "with-single-extends" }],

      // Dead imports are real removable cruft (tsconfig has noUnusedLocals off, so
      // they accumulated). unused-imports/no-unused-imports is auto-fixable, so
      // `eslint --fix` strips them. The base rule is delegated to the plugin.
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "warn",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
          caughtErrors: "all",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_"
        }
      ]
    }
  },
  // Per-file max-lines ratchet (spread last so each file's frozen ceiling wins
  // over the default 800). Regenerate via scripts/generate-max-lines-ratchet.mjs.
  ...maxLinesRatchetOverrides
);
