/**
 * Pure template-builder functions for archon workflow scaffold artifacts.
 *
 * Extracted from cli.ts (S4 extraction) to keep cli.ts under the line budget.
 * All functions are pure (no fs access, no external deps) and can be tested
 * in isolation. cli.ts imports these and calls them from the scaffold commands.
 *
 * Exported for unit-testing and for cli.ts import.
 */

export function replaceTemplateTaskId(templateContent: string, taskId: string): string {
  return templateContent.replaceAll("<task-id>", taskId);
}

export function buildBriefFromTemplate(templateContent: string, taskId: string): string {
  return replaceTemplateTaskId(templateContent, taskId).replace(
    "Original user ask:",
    "Original user ask:\n\nFill in the substantive user request here."
  );
}

export function buildPlanArtifact(taskId: string): string {
  return [
    "# Plan",
    "",
    "## Task ID",
    "",
    `\`${taskId}\``,
    "",
    "## Goal",
    "",
    "Fill in the concrete execution plan for this task before claiming completion.",
    "",
    "## Steps",
    "",
    "- record the implementation slices you will run",
    "- record the verification commands you will use",
    "- keep the plan aligned with the live task packet"
  ].join("\n");
}

export function fillEmptySection(content: string, heading: string, body: string): string {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return content.replace(new RegExp(`(${escaped}\n\n)(?=(?:## |### |$))`), `$1${body}\n\n`);
}

export function replaceSectionBody(content: string, heading: string, body: string): string {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return content.replace(new RegExp(`(${escaped}\n\n)([\\s\\S]*?)(?=\n## |\n### |$)`), `$1${body}\n`);
}

export function buildTaskFromTemplate(templateContent: string, taskId: string): string {
  const scaffolded = replaceTemplateTaskId(templateContent, taskId)
    .replace("`<owner-role>`", "`planner`")
    .replace("`artifact_complete | specialist_verified`", "`artifact_complete`")
    .replace("`strict | dual | legacy`", "`strict`")
    .replace("review_exports=required | runtime_optional", "review_exports=required");

  const hydrated = [
    ["## Goal", `Seed starter workflow metadata for \`${taskId}\` and replace these defaults before claiming completion.`],
    ["## Inputs", "- scaffold-workflow generated artifact set\n- repo-specific context to be filled before execution"],
    ["## Dependencies", "- none yet; add upstream tasks or runtime prerequisites before execution"],
    ["## Outputs", "- a specialized task packet, brief, plan, and review set for the real work"],
    ["## Coverage impact", "- establishes starter workflow coverage only; replace with task-specific impact before execution"],
    ["## Touched ledger items", "- workflow:scaffolded-task-packet"],
    ["## Required runtime traces", "- none yet; add task-specific runtime traces or state why none are required"],
    ["## Progress proof", "- replace with the first concrete progress proof once substantive execution starts"],
    ["## Interrupt checkpoint policy", "- checkpoint before any substantive write beyond the scaffolded workflow artifacts"],
    ["## Allowed write scope", "- specialize this section before implementation; scaffold only covers workflow artifact setup"],
    ["## Out of scope", "- substantive product or code changes outside the eventual task-specific write scope"],
    ["## Acceptance criteria", "- replace scaffold defaults with task-specific completion criteria before execution"],
    ["## UI surface", "`none`"],
    ["## Playwright requirement", "`false`"],
    [
      "## Browser evidence expectations",
      "- not required for the scaffolded default; replace this block if the task becomes UI-affecting"
    ],
    ["## Verification steps", "- update with the exact commands, fixtures, and runtime proofs for this task"],
    ["## Security checks", "- confirm the scaffold does not widen trust boundaries or write scope unintentionally"],
    ["## Retrieval guidance", "- prefer runtime authority and task-local artifacts over narrative summaries when they disagree"],
    ["## Anti-patterns to avoid", "- leaving scaffold placeholders in place once the task moves into execution"],
    ["## Rollback notes", "- delete or regenerate the scaffolded workflow artifacts if this task is abandoned or replaced"],
    ["### Claim", `A specialized workflow packet for \`${taskId}\` must be completed before this task can be executed safely.`],
    ["### Facts", "- this artifact was generated by scaffold-workflow\n- the seeded values are starter defaults only"],
    ["### Assumptions", "- a manager or planner will replace the seeded defaults with task-specific content before execution"],
    ["### Hypotheses and alternatives", "- best path: specialize this scaffold in place before implementation\n- alternative: delete and regenerate the workflow artifacts if the task scope changes materially"],
    ["### Evidence refs", "- scaffold-workflow generated task packet template\n- installed workflow contract checks"],
    ["### Counter-evidence", "- a scaffolded packet alone is not proof that the underlying task is ready for execution"],
    ["### Confidence", "`low`"],
    ["### Verification plan", "- update the task packet with real scope and verification details\n- run the workflow checks after the packet is specialized"],
    ["### Research and debug budgets", "- implementation attempts: 1\n- verification passes: 1\n- repair loops: 1"]
  ].reduce((current, pair) => fillEmptySection(current, pair[0]!, pair[1]!), scaffolded);

  const withRoleDefaults = replaceSectionBody(hydrated, "## Required specialist roles", "- `planner`");
  const withQualityGateDefaults = replaceSectionBody(withRoleDefaults, "## Quality gates", "- `product_acceptance`");
  const withCouncilDefaults = [
    ["### Required", "`false`"],
    [
      "### Trigger rationale",
      "- scaffold-only default: replace this once the task is specialized enough to know whether council review applies"
    ],
    ["### Decision packet", "`none`"],
    ["### Council members", "`none`"],
    ["### Dissent owner", "`none`"],
    ["### Outcome", "`inherited`"],
    ["### Exception expiry", "`none`"]
  ].reduce((current, pair) => replaceSectionBody(current, pair[0]!, pair[1]!), withQualityGateDefaults);
  const withUiDefaults = replaceSectionBody(withCouncilDefaults, "## UI surface", "`none`");
  const withPlaywrightDefaults = replaceSectionBody(withUiDefaults, "## Playwright requirement", "`false`");
  return replaceSectionBody(
    withPlaywrightDefaults,
    "## Browser evidence expectations",
    "- not required for the scaffolded default; replace this block if the task becomes UI-affecting"
  );
}

export function extractMarkdownSection(content: string, heading: string): string | undefined {
  const escaped = heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = content.match(new RegExp(`${escaped}\\n\\n([\\s\\S]*?)(?=\\n## |$)`));
  return match?.[1]?.trim();
}

export function appendReasoningHardeningSections(
  content: string,
  mode: "dual" | "strict"
): string {
  if (content.includes("## Reasoning policy")) {
    return content;
  }

  const claim = extractMarkdownSection(content, "### Claim") ?? "- backfilled from legacy task packet";
  const evidenceRefs = extractMarkdownSection(content, "### Evidence refs") ?? "- none recorded yet";
  const verificationPlan =
    extractMarkdownSection(content, "### Verification plan") ??
    extractMarkdownSection(content, "## Verification steps") ??
    "- add verification evidence";
  const counterEvidence =
    extractMarkdownSection(content, "### Counter-evidence") ?? "- none recorded yet";

  const block = [
    "",
    "## Reasoning policy",
    "",
    "### Mode",
    "",
    `\`${mode}\``,
    "",
    "### Requirements",
    "",
    mode === "strict"
      ? "- require explicit reasoning block, attempt records, trace refs, verification records, critic verification, and a supported verdict before completion"
      : "- keep legacy-compatible routing while requiring explicit attempts, verification records, and a verdict for upgraded tasks",
    "",
    "### Max attempts",
    "",
    "- 3",
    "",
    "## Reasoning attempts",
    "",
    "### Attempt records",
    "",
    "- id: `attempt-1`",
    "- label: legacy reasoning upgrade backfill",
    `- hypothesis: ${claim.replace(/\n+/g, " ")}`,
    "- alternatives: add explicit competing hypotheses before final review",
    `- evidence refs: ${evidenceRefs.replace(/\n+/g, " ")}`,
    "- verification refs: verification-1",
    "- trace ref: add runtime or artifact trace ref",
    mode === "strict" ? "- outcome: inconclusive" : "- outcome: supported",
    "- summary: backfilled from legacy reasoning-quality sections during workflow upgrade",
    "",
    "### Verification records",
    "",
    "- id: `verification-1`",
    "- kind: `critic_review`",
    "- ref: add reviewer or critic evidence ref",
    mode === "strict" ? "- status: `pending`" : "- status: `passed`",
    `- summary: seeded from existing verification guidance: ${verificationPlan.replace(/\n+/g, " ")}`,
    "",
    "### Verdict",
    "",
    mode === "strict"
      ? "- status: `needs_review`"
      : "- status: `supported`",
    "- summary: upgraded from legacy semantics under the strict-by-default workflow; verify attempt, trace, and critic evidence before relying on this verdict",
    "- supporting attempt ids: `attempt-1`",
    `- blocking issues: ${counterEvidence.replace(/\n+/g, " ")}`,
    ""
  ].join("\n");

  return `${content.trimEnd()}\n${block}`;
}

export function buildReviewFromTemplate(
  templateContent: string,
  taskId: string,
  reviewerRole: "reviewer" | "qa_engineer" | "security_reviewer"
): string {
  return replaceTemplateTaskId(templateContent, taskId)
    .replace("`reviewer | qa_engineer | security_reviewer`", `\`${reviewerRole}\``)
    .replace("`<recorded-actor-id>`", "`pending-review`")
    .replace(
      "`reviewer | qa_engineer | security_reviewer | planner | solution_architect`",
      `\`${reviewerRole}\``
    )
    .replace("`summary_only | runtime_verified | legacy_backfill`", "`summary_only`")
    .replace("`pending | passed | blocked | waived`", "`pending`")
    .replace("`low | medium | high | critical`", "`low`")
    .replace("`none | manager | security_exception`", "`none`")
    .replace("`approved | blocked | waived`", "`blocked`")
    .replace(
      "## Specialist execution evidence\n\nList the evidence used to trust the claimed specialist ownership for this task.\n",
      "## Specialist execution evidence\n\nPending specialist execution evidence.\n"
    )
    .replace(
      "## Quality gate evidence\n\nList the evidence used to trust the declared quality gates for this task.\n",
      "## Quality gate evidence\n\nPending quality gate evidence.\n"
    )
    .replace(
      "## Findings\n",
      "## Findings\n\nReview has not run yet.\n\n"
    )
    .replace(
      "## Residual risk\n",
      "## Residual risk\n\nWorkflow remains blocked until this review is completed.\n\n"
    )
    .replace(
      "## Verification evidence\n\nList exact commands, fixtures, or repro steps used for this gate.\n",
      "## Verification evidence\n\nPending review execution. For Playwright-required QA reviews, cite Playwright evidence refs here.\n"
    )
    .replace(
      "## Waiver reason\n\nDo not waive a required gate without actor, actor role, authority, and explicit reason. Unauthorized waivers remain blocking.\n",
      "## Waiver reason\n\nNone.\n"
    )
    .replace(
      "## Source handoff\n\nManager-written summary of reviewer output. Cite the trusted source here when `Provenance status` is `runtime_verified`, because the markdown file alone is not proof.\n\nFor `specialist_verified` work with `runtime_verified` provenance, include a `Runtime proof:` line here that points to the same authenticated runtime artifact summarized above.\n",
      "## Source handoff\n\nPending reviewer handoff.\n"
    );
}

export function buildHappyPathFixtureBrief(taskId: string): string {
  return [
    "## Task ID",
    "",
    `\`${taskId}\``,
    "",
    "## Fixture posture",
    "",
    "Synthetic install-proof only. Do not reuse these artifacts as live workflow evidence."
  ].join("\n");
}

export function buildHappyPathFixtureTask(taskId: string): string {
  return [
    "## Task ID",
    "",
    `\`${taskId}\``,
    "",
    "## Owner role",
    "",
    "`backend_engineer`",
    "",
    "## Completion standard",
    "",
    "`specialist_verified`",
    "",
    "## Required specialist roles",
    "",
    "- `backend_engineer`",
    "- `reviewer`",
    "- `qa_engineer`",
    "- `security_reviewer`",
    "",
    "## Quality gates",
    "",
    "- `workflow_happy_path_required`",
    "- `artifact_contract_required`",
    "- `advisory_retrieval_required`",
    "",
    "## Acceptance criteria",
    "",
    "- composed happy-path command passes",
    "- fixture remains synthetic and non-authoritative",
    "",
    "## Verification steps",
    "",
    "- bash scripts/check-archon-happy-path.sh",
    "",
    "## Required reviews",
    "",
    "- reviewer",
    "- qa_engineer",
    "- security_reviewer",
    "",
    "## Rollback notes",
    "",
    "- delete the synthetic fixture artifacts"
  ].join("\n");
}

export function buildHappyPathFixtureReview(
  taskId: string,
  reviewerRole: "reviewer" | "qa_engineer" | "security_reviewer"
): string {
  return [
    "# Review Gate",
    "",
    "## Task ID",
    "",
    `\`${taskId}\``,
    "",
    "## Reviewer role",
    "",
    `\`${reviewerRole}\``,
    "",
    "## Actor",
    "",
    "`synthetic-install-fixture`",
    "",
    "## Actor role",
    "",
    `\`${reviewerRole}\``,
    "",
    "## Provenance status",
    "",
    "`summary_only`",
    "",
    "## Review state",
    "",
    "`blocked`",
    "",
    "## Severity",
    "",
    "`low`",
    "",
    "## Findings",
    "",
    "- Synthetic install fixture only; replace with authenticated runtime review evidence before live work.",
    "",
    "## Residual risk",
    "",
    "Residual risk remains fully open because this fixture is not authenticated reviewer evidence.",
    "",
    "## Verification evidence",
    "",
    `- bash scripts/check-archon-happy-path.sh --task-id ${taskId}`,
    "- fixture review is intentionally non-authoritative",
    "",
    "## Specialist execution evidence",
    "",
    "- specialist handoff references reviewed files",
    "",
    "## Quality gate evidence",
    "",
    "- happy-path composition references synthetic fixture checks and retrieval smoke",
    "",
    "## Waiver authority",
    "",
    "`none`",
    "",
    "## Waiver reason",
    "",
    "None.",
    "",
    "## Decision",
    "",
    "`blocked`",
    "",
    "## Source handoff",
    "",
    "Synthetic fixture summary. No authenticated reviewer source exists for this install proof."
  ].join("\n");
}
