/**
 * Dashboard snapshot fetcher.
 *
 * In Phase 0 the dashboard is read-only: there is no live HTTP server.
 * The app fetches a static JSON snapshot from web/public/snapshot.json
 * (generated by src/forge/snapshot.ts or committed as a representative sample).
 *
 * Fetch is driven by a simple useEffect (Phase 0); Phase 1 can swap for
 * TanStack Query polling by replacing the fetch call here.
 */

import type { DashboardViewModel } from "../types/dashboard.ts";

const SNAPSHOT_URL = "/snapshot.json";

export class SnapshotFetchError extends Error {
  constructor(
    message: string,
    public readonly status?: number
  ) {
    super(message);
    this.name = "SnapshotFetchError";
  }
}

// ── Inline enum validators ────────────────────────────────────────────────────
// The Zod schema lives in src/forge/ and cannot be imported here (import wall).
// These mirror the union literals in src/forge/dashboard-contract.ts.
// If a value is added to the contract, add it here too.

const RUN_STATUSES = new Set([
  "intake", "planned", "decomposed", "ready",
  "in_progress", "review_blocked", "approved", "memorized", "done",
]);

const TASK_STATUSES = new Set([
  "ready", "in_progress", "review_blocked", "approved", "done", "blocked",
]);

const REVIEW_STATES = new Set(["pending", "passed", "blocked", "waived"]);

const REVIEW_SEVERITIES = new Set(["low", "medium", "high", "critical"]);

const GATE_ROLES = new Set(["reviewer", "security_reviewer", "qa_engineer"]);

const AUTHORITY_LABELS = new Set(["runtime_authoritative", "derived_only"]);

const PULSE_STATES = new Set(["idle", "running", "blocked", "complete"]);

const ROUTING_KINDS = new Set(["owner_dispatch", "review_dispatch", "wait"]);

const BLOCKER_KINDS = new Set([
  "review_missing", "approval_missing", "lock_conflict",
  "dependency_unresolved", "stale_recovery", "generic",
]);

// ── Field validators ──────────────────────────────────────────────────────────

function requireString(obj: Record<string, unknown>, field: string, ctx: string): string {
  const v = obj[field];
  if (typeof v !== "string" || v.length === 0) {
    throw new SnapshotFetchError(`${ctx}.${field} must be a non-empty string (got ${JSON.stringify(v)})`);
  }
  return v;
}

function requireEnum(obj: Record<string, unknown>, field: string, allowed: Set<string>, ctx: string): string {
  const v = requireString(obj, field, ctx);
  if (!allowed.has(v)) {
    throw new SnapshotFetchError(`${ctx}.${field} "${v}" is not a valid value (allowed: ${[...allowed].join(", ")})`);
  }
  return v;
}

function asObj(v: unknown, ctx: string): Record<string, unknown> {
  if (!v || typeof v !== "object" || Array.isArray(v)) {
    throw new SnapshotFetchError(`${ctx} must be a plain object`);
  }
  return v as Record<string, unknown>;
}

function asArray(v: unknown, ctx: string): unknown[] {
  if (!Array.isArray(v)) {
    throw new SnapshotFetchError(`${ctx} must be an array`);
  }
  return v;
}

// ── Sub-validators ────────────────────────────────────────────────────────────

function validateHeader(raw: unknown): void {
  const obj = asObj(raw, "header");
  requireString(obj, "runId", "header");
  requireString(obj, "title", "header");
  requireEnum(obj, "status", RUN_STATUSES, "header");
  requireEnum(obj, "authorityLabel", AUTHORITY_LABELS, "header");
  requireString(obj, "updatedAt", "header");
}

function validateBlocker(raw: unknown, i: number): void {
  const ctx = `blockers[${i}]`;
  const obj = asObj(raw, ctx);
  requireString(obj, "id", ctx);
  requireEnum(obj, "kind", BLOCKER_KINDS, ctx);
  requireString(obj, "reason", ctx);
  asArray(obj["nextActions"], `${ctx}.nextActions`);
  // taskId is optional — skip if absent
  if ("taskId" in obj && obj["taskId"] !== undefined) {
    requireString(obj, "taskId", ctx);
  }
}

function validateTaskQueueEntry(raw: unknown, i: number): void {
  const ctx = `taskQueue[${i}]`;
  const obj = asObj(raw, ctx);
  requireString(obj, "taskId", ctx);
  requireString(obj, "title", ctx);
  requireEnum(obj, "status", TASK_STATUSES, ctx);
  requireString(obj, "ownerRole", ctx);
  // routingRecommendation is optional
  if ("routingRecommendation" in obj && obj["routingRecommendation"] !== undefined) {
    requireEnum(obj, "routingRecommendation", ROUTING_KINDS, ctx);
  }
  asArray(obj["blockers"], `${ctx}.blockers`);
  requireString(obj, "updatedAt", ctx);
}

function validateReviewGate(raw: unknown, i: number): void {
  const ctx = `reviewGates[${i}]`;
  const obj = asObj(raw, ctx);
  requireEnum(obj, "role", GATE_ROLES, ctx);
  requireEnum(obj, "state", REVIEW_STATES, ctx);
  // severity is optional
  if ("severity" in obj && obj["severity"] !== undefined) {
    requireEnum(obj, "severity", REVIEW_SEVERITIES, ctx);
  }
  requireString(obj, "taskId", ctx);
  // actor, reviewedAt are optional strings
}

function validatePulse(raw: unknown): void {
  const obj = asObj(raw, "pulse");
  requireEnum(obj, "pulseState", PULSE_STATES, "pulse");
  const lockCount = obj["activeLockCount"];
  if (typeof lockCount !== "number" || !Number.isInteger(lockCount) || lockCount < 0) {
    throw new SnapshotFetchError(`pulse.activeLockCount must be a non-negative integer (got ${JSON.stringify(lockCount)})`);
  }
  asArray(obj["lockedTaskIds"], "pulse.lockedTaskIds");
}

// ── Main validator ────────────────────────────────────────────────────────────

function validateSnapshot(raw: unknown): DashboardViewModel {
  const obj = asObj(raw, "snapshot");

  validateHeader(obj["header"]);

  const blockers = asArray(obj["blockers"], "blockers");
  blockers.forEach((b, i) => validateBlocker(b, i));

  const taskQueue = asArray(obj["taskQueue"], "taskQueue");
  taskQueue.forEach((t, i) => validateTaskQueueEntry(t, i));

  const reviewGates = asArray(obj["reviewGates"], "reviewGates");
  reviewGates.forEach((g, i) => validateReviewGate(g, i));

  validatePulse(obj["pulse"]);

  return raw as DashboardViewModel;
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function fetchDashboardSnapshot(): Promise<DashboardViewModel> {
  const response = await fetch(SNAPSHOT_URL);

  if (!response.ok) {
    throw new SnapshotFetchError(
      `Failed to fetch dashboard snapshot: HTTP ${response.status}`,
      response.status
    );
  }

  const raw: unknown = await response.json();

  // Full structural + enum validation (item 7).
  // Throws SnapshotFetchError with a precise field-level message on any bad value.
  return validateSnapshot(raw);
}
