/**
 * @module admin/why-redaction
 *
 * Secret redaction for `archon why` (audit F9). TERMINAL DESIGN (round 8,
 * mechanically hardened in rounds 9-11) — see
 * `src/admin/why-redaction-design-history.md` for the full round-1-through-11
 * evolution narrative; this header states only the CURRENT contract.
 *
 * MODEL: vocabulary-anchored default-deny. Stage 1 (`applySecretMarkerRules`)
 * runs high-confidence context markers (credential URLs, AWS key ids,
 * well-known secret-token prefixes, labeled `key=value` fields,
 * Authorization/Bearer headers, mysqldump's `-p<value>`) as defense-in-depth,
 * vocabulary-aware since round 9 (a captured value that is an exact
 * `knownSafeTokens` member survives even next to a keyword). Stage 2
 * (`classifyToken`, via `sanitizeFreeText`) then classifies every remaining
 * whitespace token against the allowlist below. A free-text token survives
 * ONLY if it is:
 *
 *   1. An EXACT member of a `knownSafeTokens` vocabulary the caller supplies
 *      — built, at diagnosis time, from the STRUCTURED context the collector
 *      already holds (task ids, run ids, role names, status/enum/outcome
 *      tokens, this module's own recommended command words, sidecar paths it
 *      constructed). See why-diagnosis.ts's `buildKnownVocabulary`.
 *   2. A flag name (`-x`, `--long-flag`) whose body does NOT itself contain a
 *      recognized secret keyword substring (round-10 fix) — a flag is a
 *      label, never a value, UNLESS a keyword embedded in it proves
 *      otherwise; see `isSafeFlagName`.
 *   3. A UUID or ISO-timestamp shape — machine-generated, not
 *      attacker-controlled. There is no bare-number shape exemption — a
 *      number survives only via vocabulary membership.
 *   4. A path whose EVERY `/`-separated segment independently passes one of
 *      these same checks — otherwise the WHOLE token redacts (never a
 *      partial per-segment redaction).
 *   5. A `scheme://host...` URL whose EVERY path/query token independently
 *      passes one of these same checks — otherwise the path+query collapses
 *      wholesale to `scheme://host/[redacted]` (the scheme+authority, which
 *      identifies WHERE not WHAT, is always kept). A URL WITH a userinfo
 *      component (`user:pass@host`) is caught by stage 1's
 *      `CREDENTIAL_URL_WITH_USERINFO` before stage 2 ever sees it.
 *
 * Everything else — any bare word, identifier, acronym, or number that
 * merely LOOKS safe — redacts. `sanitizeFreeText`/`sanitizeForDisplay`
 * default `knownSafeTokens` to an EMPTY set, so a caller that supplies no
 * vocabulary gets the strictest possible behavior; a missing vocabulary must
 * never silently fall back to "shape is enough". The keyword rules in stage
 * 1 are explicitly non-load-bearing defense-in-depth — the actual security
 * boundary is the vocabulary-anchored default-deny in stage 2, applied
 * uniformly to every free-text token. A future keyword gap (a synonym stage
 * 1 doesn't recognize) is NOT a valid finding against this design: stage 2
 * would still catch it.
 *
 * `classifyToken`'s only whole-token short-circuit is an EXACT match on the
 * `[redacted]` marker (a token stage 1 fully consumed) — a token that merely
 * CONTAINS that marker as a substring (glued to other, untouched content
 * with no whitespace) always falls through to full classification (round-9
 * fix; see the design-history doc for the CRITICAL bug this closed).
 *
 * EXEMPTION CHECKLIST (every structural shape-exemption):
 *
 *   - Flag name (`isSafeFlagName`, e.g. `--task-id`, `-h`) — a flag is a
 *     LABEL, not a value; nothing after the label has been read yet, so
 *     there is nothing to leak — UNLESS the flag body itself contains a
 *     recognized secret keyword substring (round-10 CRITICAL fix), in which
 *     case it is no longer blanket-trusted and falls through like any other
 *     token — `--firstSecretHere123-password` and `--password-secretHere`
 *     both shape-match a bare flag but glue a live secret to the keyword,
 *     using the "label" role as cover. The keyword check is now separator-
 *     tolerant (round-11 CRITICAL fix, `why-redaction-keywords.ts`). ACCEPTED
 *     TRADE-OFF (round-11 MEDIUM, owner: backend-engineer): benign compound
 *     flags like `--auth-timeout`/`--credential-source` still redact
 *     wholesale, same as round 10 — design-history's round-11 entry explains
 *     the rejected shape-based exemption.
 *   - ISO-8601 timestamp (`SAFE_ISO_TIMESTAMP`, fractional seconds bounded
 *     to 1-9 digits) — machine-generated by the runtime's own clock, never
 *     something an attacker supplies as a secret. The ONLY numeric-adjacent
 *     shape still safe without vocabulary backing — a bare integer/decimal
 *     is not.
 *   - UUID (`SAFE_UUID`) — fixed-width, every group is `{n}`, exactly 36
 *     characters total; machine-generated, and the fixed width leaves no
 *     room to smuggle variable-length secret data.
 *   - Path segment / URL path-query token (`isBoundedSafeShape`, reused by
 *     `isSafePathToken`/`classifyUrlToken`) — a vocabulary member, UUID, or
 *     ISO timestamp appearing as ONE segment/token of an otherwise path- or
 *     URL-shaped token. A path or URL survives WHOLE only if EVERY one of
 *     its segments/tokens independently passes this check; otherwise the
 *     entire token (or, for URLs, the entire path+query) redacts. Length is
 *     deliberately UNBOUNDED at the path/URL-structure level — real paths
 *     and URLs are legitimately long, and the actual security-relevant
 *     restriction is exclusion of `@`/`:` (credential-bearing shapes), not
 *     length. See the residual note below.
 *   - Shell operator (`SHELL_OPERATOR`) — pure punctuation with no
 *     alphanumeric content; there is no character budget left to carry a
 *     secret.
 *
 * BOUNDEDNESS AUDIT (every SAFE_* shape regex, bounded or justified):
 *
 *   | Pattern               | Bounded?                  | Why
 *   |-----------------------|---------------------------|---------------------------------------
 *   | SAFE_UUID             | yes, fixed-width          | every group is `{n}`; exactly 36 chars total
 *   | SAFE_ISO_TIMESTAMP    | yes, fraction ≤9 digits   | fractional-seconds group is bounded, never unbounded `\d+`
 *   | isSafeFlagName        | N/A — label, not a value  | nothing has been read yet; EXCLUDES bodies containing a keyword substring (round-10), separator-tolerant (round-11)
 *   | SAFE_FLAG_VALUE_PAIR  | N/A — splitter, not a gate| the extracted value is re-validated independently
 *   | SHELL_OPERATOR        | yes, closed alphabet      | punctuation-only; zero alphanumeric content
 *   | PATH_LIKE_SHAPE       | N/A — gate, not a grant   | only decides ELIGIBILITY for per-segment checks
 *   | URL_STRUCTURE         | N/A — gate, not a grant   | only decides ELIGIBILITY for per-token checks
 *   (there is no `SAFE_NUMBER` and no blanket `SAFE_PATH`/`SAFE_URL_NO_USERINFO`
 *   — a bare number/path/URL is never safe by shape alone; see the allowlist above)
 *
 * RESIDUAL, ACCEPTED TRADE-OFF (final disclosure): nothing survives by shape
 * alone except an exact vocabulary member, an ISO timestamp, a UUID, a flag
 * name, or a path/URL every one of whose segments/tokens independently
 * passes one of those same checks. A bare number — no matter how short — has
 * no shape-only path to survival; it must be vouched for by the vocabulary,
 * exactly like any other unrecognized token. The one remaining residual:
 * paths and URLs are deliberately UNBOUNDED in length (bounding them would
 * break real, legitimately long paths and URLs), so an unlabeled secret with
 * no recognized keyword, formatted to look like a long path segment or a URL
 * query token that ALSO happens to be a vocabulary member or a UUID/
 * timestamp shape, is still a residual (an extremely narrow, already-
 * accepted case — a secret would have to itself collide with a bounded safe
 * shape, not merely look path/URL-adjacent). Free-text numbers ("retried 3
 * times") and unknown paths redact by design; structured evidence
 * (why-diagnosis.ts's `structured()`) is unaffected by any of this — it
 * never calls `sanitizeFreeText`; the sidecar pointer already present in
 * every cause's evidence remains the relief valve for the raw original text.
 */

import { scrubPgCredentials } from "./db-error-scrub.ts";
import { SECRET_KEYWORD_ALTERNATION } from "./why-redaction-keywords.ts";

export const MAX_COMMAND_DISPLAY_LENGTH = 120;

/** The default vocabulary for callers that don't supply one — deliberately
 * empty, so "no vocabulary given" means "strictest possible redaction", never
 * a silent fallback to shape-only trust. */
const EMPTY_VOCABULARY: ReadonlySet<string> = new Set();

// ---------------------------------------------------------------------------
// Stage 1 — high-confidence secret markers. Run BEFORE tokenization; redact
// by pattern/context regardless of vocabulary. Kept from round 2/3/4 (URL
// credentials, labeled fields, Authorization/Bearer, mysqldump -p); extended
// in round 5 (well-known secret-token prefixes; userinfo-scoped credential
// URLs) and round 6 (space-separated labeled flags, see finding 1b below).
// ---------------------------------------------------------------------------

// SECRET_KEYWORD_ALTERNATION now lives in why-redaction-keywords.ts (round-11
// fix): separator-tolerant (`pass-word`/`to-ken` match unsplit), ONE shared
// source fixing every consulting site at once.

// Round-10 CRITICAL fix (part a): the label-capture halves around the
// keyword used to be UNBOUNDED (`[\w-]*`), which could absorb arbitrary
// preceding/following content into what the rule then treats as an inert
// "label" and never re-examines — `--firstSecretHere123-password
// verysecretvalue` glued a live secret to the keyword via a hyphen, landing
// entirely inside the unbounded prefix, which stage 1 emitted back
// UNCHANGED (only the trailing "value" half was ever substituted). Bounded
// to `{0,12}` each side — generous enough for real compound identifiers
// this rule exists to catch (`PG` + `PASSWORD`, `MYSQL_` + `PWD`, `AWS_` +
// `SECRET` + `_ACCESS_KEY`, all well under 12 chars), but too tight for an
// attacker to smuggle a meaningful secret fragment through as "label
// context" — and short enough that a label needing MORE than 12 chars on
// either side of the keyword to reach the actual `:`/`=`/whitespace
// boundary simply fails to match at all, falling through untouched to
// stage 2's default-deny (see `isSafeFlagName`, the stage-2 backstop for
// this same bypass class).
const LABELED_FIELD_PATTERN = new RegExp(
  `\\b([\\w-]{0,12}(?:${SECRET_KEYWORD_ALTERNATION})[\\w-]{0,12})(\\s*[:=]\\s*)([^\\s"'\`]+)`,
  "gi"
);

// Round-6 gate finding 1b: LABELED_FIELD_PATTERN only fires on a `:`/`=` join
// — it never covered the CLI convention of a space-separated secret-labeled
// flag and its value (`--token 8372150`, `--password hunter2Aa1`, `--key
// <v>`, `--secret <v>`). Redacts the value regardless of its own shape, so a
// short (in-bound) numeric OTP/PIN passed as a flag value is caught even
// though `SAFE_NUMBER`'s bound alone would have let it through. Round-10:
// bounded `{0,12}` each side of the keyword for the same reason as
// `LABELED_FIELD_PATTERN` above.
const SPACE_SEPARATED_SECRET_FLAG = new RegExp(
  `(--?[\\w-]{0,12}(?:${SECRET_KEYWORD_ALTERNATION})[\\w-]{0,12})(\\s+)([^\\s"'\`]+)`,
  "gi"
);

// Round-7 gate finding 2: the keyword list above gained `pin`/`otp`/etc, but
// "code" itself was deliberately NOT added — bare `code` would collide with
// this codebase's own `exit-code`/`error-code`/`status-code` vocabulary. This
// scoped pair covers "pin code"/"otp code"/"verification code"/"auth code"
// as a COMPOUND phrase (colon/equals-joined and space-joined) without ever
// matching bare `code`, since the phrase requires one of these four specific
// words immediately before it.
const CODE_ADJACENT_KEYWORDS = "pin|verification|otp|auth";

const LABELED_CODE_PHRASE_PATTERN = new RegExp(
  `\\b((?:${CODE_ADJACENT_KEYWORDS})[\\s-]*code)(\\s*[:=]\\s*)([^\\s"'\`]+)`,
  "gi"
);

const SPACE_SEPARATED_CODE_PHRASE_PATTERN = new RegExp(
  `\\b((?:${CODE_ADJACENT_KEYWORDS})[\\s-]*code)(\\s+)([^\\s"'\`]+)`,
  "gi"
);

// Round-8 gate finding 1 (root-cause fix, filler-word regex bug): a
// recognized secret keyword followed by 0-2 filler words (pure letters —
// never itself an already-redacted "[redacted]" marker or a flag) then a
// value token redacts that value. Round 7 required AT LEAST ONE filler word
// (`{1,2}`), which silently missed the ZERO-filler case — a bare, unprefixed
// "password hunter2Aa1" or "PIN 482913" (keyword directly adjacent to its
// value, no "is"/"code" in between, no leading dash) matched neither this
// rule (needed a filler) nor SPACE_SEPARATED_SECRET_FLAG (needed a leading
// dash), so it leaked. `{0,2}` closes that gap at the regex level — this is
// a correctness fix to the pattern itself, independent of and in addition to
// round 8's numeric-exemption removal below (which is what actually makes
// this whole keyword-adjacency family NON-LOAD-BEARING for numeric secrets —
// see the module header's "keyword rules are defense-in-depth only" note).
const PROSE_SECRET_KEYWORD_PATTERN = new RegExp(
  `(\\b(?:${SECRET_KEYWORD_ALTERNATION})\\b(?:\\s+[A-Za-z]+){0,2}\\s+)([^\\s"'\`]+)`,
  "gi"
);

// A `scheme://...` URL that carries a userinfo component (`user:pass@host` or
// `user@host`) — generalizes round-3's Postgres-only reuse of
// scrubPgCredentials to mysql://, mongodb://, mongodb+srv://, redis://,
// https://user:pass@..., etc. Requires an `@` inside the authority segment
// (before the first `/` or whitespace) so a credential-FREE URL is left
// alone for stage 2's `SAFE_URL_NO_USERINFO` to allowlist instead (round-5
// MEDIUM fix — round 4's version redacted every URL unconditionally).
// scrubPgCredentials runs first so the Postgres case keeps its existing,
// slightly friendlier "postgres://[redacted]" partial-redaction shape; this
// is the generic backstop for every other scheme.
const CREDENTIAL_URL_WITH_USERINFO = /\b([a-z][a-z0-9+.-]*):\/\/[^\s"'`/@]*@[^\s"'`]*/gi;

// AWS access-key-id-shaped tokens (AKIA/ASIA/AGPA/AIDA/AROA/ANPA/ANVA
// prefixes are all real AWS credential-type prefixes) — redacted regardless
// of surrounding context, since these are unambiguously credential material
// wherever they appear.
const AWS_KEY_ID_PATTERN = /\b(AKIA|ASIA|AGPA|AIDA|AROA|ANPA|ANVA)[A-Z0-9]{12,}\b/g;

// Well-known secret-token prefixes (round-5 gate's own adversarial probes:
// GitHub personal-access tokens, Stripe-style live keys, Anthropic API keys,
// npm tokens). Cheap, loud, defense-in-depth: even if a token like this
// appears in ordinary prose ("token ghp_XXXX is invalid"), it is redacted by
// context marker alone, before stage 2 ever has to reason about vocabulary.
const WELL_KNOWN_SECRET_PREFIX_PATTERN = /\b(ghp_|gho_|ghu_|ghs_|ghr_|sk_live_|sk_test_|sk-ant-|npm_)[A-Za-z0-9_-]+/g;

// mysqldump/mysql's `-p<password>` concatenated-value flag (no `=`, no space
// before the value) — round-4 adversarial fixture. Deliberately broad: any
// `-p<non-whitespace>` token is treated as this flag and its value redacted,
// even though this occasionally over-redacts an unrelated `-p` flag from
// another CLI (e.g. `-port`). Over-redaction here is the accepted trade-off;
// silently letting a password through because it wasn't preceded by "=" is not.
const MYSQL_CONCAT_PASSWORD_FLAG = /(^|\s)(-p)([^\s"'`]+)/g;

/** Round-9 HIGH fix: stage 1's labeled/space-separated/prose keyword rules
 * used to redact any value adjacent to a keyword UNCONDITIONALLY — they had
 * no visibility into `knownSafeTokens` at all, so a legitimate vocabulary
 * member (a task id, run id, or other structured value the collector itself
 * vouches for) redacted just because it happened to sit next to a keyword
 * (`"password task-abc123"` destroyed `task-abc123` even though stage 2
 * alone would have correctly kept it). A value that is an EXACT vocabulary
 * member survives even in a keyword-adjacent position — it is OUR id; it
 * cannot be the secret the keyword is labeling. `extractTokenCore` strips
 * incidental trailing punctuation (a comma, a period) before the membership
 * check, mirroring how stage 2 tokenizes, so a vocabulary value followed by
 * ordinary prose punctuation still matches. */
function redactValueUnlessVocabulary(value: string, knownSafeTokens: ReadonlySet<string>): string {
  return knownSafeTokens.has(extractTokenCore(value)) ? value : "[redacted]";
}

function applySecretMarkerRules(text: string, knownSafeTokens: ReadonlySet<string>): string {
  let result = scrubPgCredentials(text);
  result = result.replace(
    CREDENTIAL_URL_WITH_USERINFO,
    (_match, scheme: string) => `${scheme.toLowerCase()}://[redacted]`
  );
  result = result.replace(AWS_KEY_ID_PATTERN, "[redacted]");
  result = result.replace(WELL_KNOWN_SECRET_PREFIX_PATTERN, "[redacted]");
  result = result.replace(
    LABELED_CODE_PHRASE_PATTERN,
    (_match, label: string, sep: string, value: string) => `${label}${sep}${redactValueUnlessVocabulary(value, knownSafeTokens)}`
  );
  result = result.replace(
    SPACE_SEPARATED_CODE_PHRASE_PATTERN,
    (_match, label: string, sep: string, value: string) => `${label}${sep}${redactValueUnlessVocabulary(value, knownSafeTokens)}`
  );
  result = result.replace(
    LABELED_FIELD_PATTERN,
    (_match, label: string, sep: string, value: string) => `${label}${sep}${redactValueUnlessVocabulary(value, knownSafeTokens)}`
  );
  result = result.replace(
    SPACE_SEPARATED_SECRET_FLAG,
    (_match, flag: string, sep: string, value: string) => `${flag}${sep}${redactValueUnlessVocabulary(value, knownSafeTokens)}`
  );
  result = result.replace(
    PROSE_SECRET_KEYWORD_PATTERN,
    (_match, prefix: string, value: string) => `${prefix}${redactValueUnlessVocabulary(value, knownSafeTokens)}`
  );
  result = result.replace(/\bAuthorization:\s*[^\s"'`]+(?:\s+[^\s"'`]+)?/gi, "Authorization: [redacted]");
  result = result.replace(/\bBearer\s+[^\s"'`]+/gi, "Bearer [redacted]");
  result = result.replace(
    MYSQL_CONCAT_PASSWORD_FLAG,
    (_match, lead: string, flag: string, value: string) => `${lead}${flag}${redactValueUnlessVocabulary(value, knownSafeTokens)}`
  );
  return result;
}

// ---------------------------------------------------------------------------
// Stage 2 — vocabulary-anchored default-deny. Every token stage 1 didn't
// already redact is classified here. See the module header for the full
// allowlist contract and disclosure.
// ---------------------------------------------------------------------------

const SAFE_UUID = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

/** ISO-8601 timestamp shape, with optional fractional seconds and a
 * `Z`/offset suffix — e.g. `2026-07-04T12:34:56.789Z`. Machine-generated,
 * not attacker-controlled, so safe by shape alone regardless of vocabulary
 * (round-5 fix: round 4 only allowlisted bare numbers, so a full timestamp
 * fell through to redaction; round-7 bounded the fractional-seconds group to
 * 1-9 digits, closing an identical unbounded-digit-run bypass). This is the
 * ONLY numeric-adjacent shape that still survives without vocabulary backing
 * (round-8 terminal design) — a bare integer or decimal no longer does. */
const SAFE_ISO_TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,9})?(?:Z|[+-]\d{2}:?\d{2})?$/;

/** Bare flag shape (`--task-id`, `-h`, `--apply-safe`) — a GATE, not a grant;
 * see `isSafeFlagName` below, which adds the round-10 keyword exclusion. */
const SAFE_FLAG_SHAPE = /^--?[A-Za-z][A-Za-z0-9-]*$/;

/** Matches any recognized secret keyword ANYWHERE in a token, case-
 * insensitive — used only to DISQUALIFY a flag-shaped token from the
 * blanket "flags are just labels" trust, never to grant safety itself.
 * Separator-tolerant (round-11 CRITICAL fix) — `pass-word`/`to-ken` no
 * longer defeat this by splitting the word. */
const SECRET_KEYWORD_ANYWHERE = new RegExp(SECRET_KEYWORD_ALTERNATION, "i");

/** Matches a flag body that IS, EXACTLY, one recognized secret keyword and
 * nothing else (`token`, `password`, `api-key`, `access_key`, …) — the
 * designed, legitimate case (`--token <value>`, `--password <value>`,
 * `--api-key <value>`): the flag name IS the label naming its own value,
 * with no extra glued content on either side. Also separator-tolerant
 * (round-11) — `--pass-word` alone is as legitimate a bare label as `--password`. */
const BARE_SECRET_KEYWORD = new RegExp(`^(?:${SECRET_KEYWORD_ALTERNATION})$`, "i");

/** Round-10 CRITICAL fix (part b): a flag name is a LABEL, not a value —
 * nothing after it has been read yet, so it was previously trusted by
 * shape alone regardless of length or content. That trust is exactly what
 * `--firstSecretHere123-password` and `--password-secretHere` exploit: both
 * shape-match a bare flag (dashes + alnum + hyphens) while gluing a live
 * secret fragment directly against a recognized keyword, using the "it's
 * just a label" grant as cover — NEITHER is the flag simply BEING the
 * keyword (`--token`, `--password`, `--api-key`), which remains safe by
 * design (round 6's whole labeled-flag mechanism depends on it). The
 * distinguishing test: if the flag body, entirely, IS one recognized
 * keyword, it is a legitimate label with nothing else attached. Any OTHER
 * keyword-substring embedding — a prefix or suffix glued to the keyword —
 * is no longer blanket-trusted and falls through to the same default-deny
 * path as any other token (bounded shape / vocabulary / catch-all). */
function isSafeFlagName(token: string): boolean {
  if (!SAFE_FLAG_SHAPE.test(token)) return false;
  const body = token.replace(/^--?/, "");
  if (BARE_SECRET_KEYWORD.test(body)) return true;
  return !SECRET_KEYWORD_ANYWHERE.test(body);
}

/** `--flag=value` — a SPLITTER, not a gate: both halves are re-validated
 * independently. The flag half is only safe if `isSafeFlagName` accepts it
 * (round-10: no longer trusted by dash-prefix shape alone — see
 * `isSafeFlagName`); the value half must still pass `isSafeValueShape` on
 * its own (vocabulary or structural shape). */
const SAFE_FLAG_VALUE_PAIR = /^(--?[A-Za-z][A-Za-z0-9-]*)=([\s\S]*)$/;

/** Pure shell syntax (redirects, pipes, `&&`, bare `--`) — cannot itself carry
 * a secret since it has no alphanumeric content. */
const SHELL_OPERATOR = /^[-&|;<>()]+$/;

/** The bounded, non-vocabulary shapes that can still prove safety on their
 * own: an exact vocabulary member, a UUID (fixed-width, machine-generated),
 * or an ISO timestamp (fixed-format, machine-generated). Reused both for
 * plain-token classification AND for classifying the individual SEGMENTS of
 * a path or the individual TOKENS inside a URL's path/query (round-8 finding
 * 2) — "bounded safe shape" is now one well-defined concept applied
 * uniformly everywhere a value needs proving, not a per-context ad hoc list. */
function isBoundedSafeShape(token: string, knownSafeTokens: ReadonlySet<string>): boolean {
  return knownSafeTokens.has(token) || SAFE_UUID.test(token) || SAFE_ISO_TIMESTAMP.test(token);
}

/** Shape GATE (not a safety grant) for "this token looks like a path" —
 * absolute, `./`/`../`-relative, or bare relative, with at least one internal
 * `/`, built from path-safe characters, excluding `@` and `:` (the two
 * characters that signal a credential-bearing URL/connection-string shape).
 * Passing this gate only means the token is ELIGIBLE for per-segment
 * analysis in `isSafePathToken` below — round-8 finding 2 removed the old
 * blanket "any path-shaped token survives" allowlist (round-5/6's `SAFE_PATH`
 * granted safety by shape alone; that is gone). */
const PATH_LIKE_SHAPE = /^\.{0,2}\/?[A-Za-z0-9_.-]+(?:\/[A-Za-z0-9_.-]+)+\/?$/;

/** Round-8 finding 2: a free-text path survives ONLY if EVERY segment is a
 * vocabulary member or a bounded safe shape (UUID/ISO-timestamp) — otherwise
 * the ENTIRE token redacts (never a per-segment partial redaction, which
 * would fragment the path into something unreadable and still leak the
 * segments that "happened" to look safe). In practice: a collector-
 * constructed sidecar path (e.g. `.archon/work/daemon/hook-blocker-
 * state.json`) is added to the vocabulary as ONE WHOLE STRING by
 * `tokenizeToVocabulary` (it contains no whitespace, so it is never split
 * into per-segment vocabulary entries) — so real evidence paths render via
 * plain exact-match membership, checked before this function is ever called.
 * This per-segment path is the fallback for a path-shaped token that is NOT
 * already a whole-string vocabulary member. */
function isSafePathToken(token: string, knownSafeTokens: ReadonlySet<string>): boolean {
  if (!PATH_LIKE_SHAPE.test(token)) return false;
  const segments = token.split("/").filter((segment) => segment.length > 0);
  if (segments.length === 0) return false;
  return segments.every((segment) => isBoundedSafeShape(segment, knownSafeTokens));
}

/** `scheme://authority...` structure — captures the scheme, the authority
 * segment (host[:port], no userinfo — a URL WITH userinfo is caught by
 * stage 1's `CREDENTIAL_URL_WITH_USERINFO` before this ever runs), and
 * everything after the authority (the path+query "rest", if any). */
const URL_STRUCTURE = /^([A-Za-z][A-Za-z0-9+.-]*):\/\/([^\s"'`@/]*)(\/[^\s"'`]*)?$/;

/** Round-8 finding 2: a URL's authority (scheme + host) is safe by shape —
 * it identifies WHERE, not WHAT — but the path+query is free-text content an
 * attacker (or an accidental leak) can put anything into, including an
 * unlabeled secret as a query value. Round-5/6's `SAFE_URL_NO_USERINFO`
 * granted the ENTIRE URL a blanket pass once userinfo was absent; that
 * blanket pass is gone. Now: split the "rest" (path+query) into its
 * component tokens and require EVERY one to be a vocabulary member or a
 * bounded safe shape. If they all pass, the whole URL survives unchanged.
 * If any fails, the path+query is dropped wholesale to a single
 * `[redacted]` marker — `scheme://host/[redacted]` — rather than partially
 * redacting individual tokens (which would still disclose the URL's overall
 * shape/structure to a degree not worth the complexity). Returns `undefined`
 * when the token isn't URL-shaped at all, so the caller falls through to
 * other checks.
 *
 * Round-9 MEDIUM fix: this function's wholesale-collapse contract was always
 * what the CODE here did; the observed mismatch was that `classifyToken`'s
 * old blanket `[redacted]`-substring short-circuit bypassed this function
 * ENTIRELY for a URL where stage 1 had already partially redacted one
 * key=value pair, returning that raw, partially-redacted stage-1 output
 * unchanged instead of ever calling `classifyUrlToken` on it — which looked,
 * from the outside, like "partial in-place redaction" even though this
 * function itself has never had a partial-redaction code path. Narrowing
 * that short-circuit to an exact-match check (round-9 CRITICAL fix, see
 * `classifyToken`) means this function is now ALWAYS the one deciding a
 * URL-shaped token's fate, so its behavior and this doc comment are now
 * unconditionally in sync — there is no remaining call path that bypasses
 * the wholesale-collapse contract described above. */
function classifyUrlToken(token: string, knownSafeTokens: ReadonlySet<string>): string | undefined {
  // Whole-string vocabulary membership wins immediately, same as every other
  // shape check — a collector-constructed URL added to the vocabulary as ONE
  // STRING (it contains no whitespace, so `tokenizeToVocabulary` never splits
  // it) must not be needlessly decomposed into path/query tokens that aren't
  // separately in the vocabulary.
  if (knownSafeTokens.has(token)) return token;
  const match = URL_STRUCTURE.exec(token);
  if (!match) return undefined;
  const scheme = match[1] ?? "";
  const authority = match[2] ?? "";
  const rest = match[3];
  if (!rest) {
    // Bare `scheme://authority` with nothing after it — nothing to redact.
    return `${scheme.toLowerCase()}://${authority}`;
  }
  const restTokens = rest.split(/[/?&=]/).filter((piece) => piece.length > 0);
  const allSafe = restTokens.every((piece) => isBoundedSafeShape(piece, knownSafeTokens));
  if (allSafe) {
    return `${scheme.toLowerCase()}://${authority}${rest}`;
  }
  return `${scheme.toLowerCase()}://${authority}/[redacted]`;
}

function isSafeValueShape(token: string, knownSafeTokens: ReadonlySet<string>): boolean {
  return isBoundedSafeShape(token, knownSafeTokens) || isSafePathToken(token, knownSafeTokens);
}

const TOKEN_WRAPPER_PATTERN = /^([`"'(]*)([\s\S]*?)([`"'),.;]*)$/;

/**
 * Strips wrapper punctuation (quotes, backticks, parens, trailing prose
 * punctuation) from one whitespace-delimited token, returning its bare
 * "core". Exported so a caller building a `knownSafeTokens` vocabulary from
 * static command/path strings tokenizes IDENTICALLY to how free text is
 * scanned — a vocabulary entry tokenized differently would silently never
 * match (see `tokenizeToVocabulary` below).
 */
export function extractTokenCore(token: string): string {
  const match = TOKEN_WRAPPER_PATTERN.exec(token);
  return match?.[2] ?? token;
}

/**
 * Splits `text` on whitespace and extracts each token's bare core (dropping
 * empties) — the standard way to turn a static command template or sidecar
 * path string into vocabulary entries for `sanitizeFreeText`'s allowlist.
 */
export function tokenizeToVocabulary(text: string): string[] {
  return text
    .split(/\s+/)
    .map((piece) => extractTokenCore(piece))
    .filter((core) => core.length > 0);
}

/**
 * Classifies one whitespace-delimited token against the vocabulary + shape
 * allowlist. Wrapper punctuation is stripped before classification and
 * reattached after.
 *
 * Round-9 CRITICAL fix: a token whose core is EXACTLY the `[redacted]`
 * marker (stage 1 fully consumed it — nothing else to analyze) is left
 * alone. A token that merely CONTAINS `[redacted]` as a substring, glued to
 * OTHER untouched content with no whitespace (e.g. a URL query string where
 * stage 1's labeled-field rule redacted one `key=value` pair but left a
 * neighboring `&otherKey=stillLiveSecret` pair untouched in the SAME
 * whitespace token), is NOT given a free pass — it falls through to full
 * classification below, exactly like any other token. Every branch below
 * (`classifyUrlToken`'s per-piece analysis, the flag-value split, the final
 * catch-all) already replaces its ENTIRE matched scope rather than leaving
 * fragments, so re-running this pipeline on a partially-redacted token
 * correctly re-examines — and if unsafe, fully collapses — the untouched
 * remainder rather than exempting the whole token because ONE fragment of it
 * happened to already read `[redacted]`. The prior blanket
 * `core.includes("[redacted]")` short-circuit was the bug: it treated any
 * substring match as whole-token clearance, letting the untouched remainder
 * of a mixed token leak in full (live repro: `https://x.com/callback?
 * state=<secret>&password=<secret>` — stage 1 catches only the `password`
 * value; the old code then let `state=<secret>` through unexamined).
 */
function classifyToken(token: string, knownSafeTokens: ReadonlySet<string>): string {
  const match = TOKEN_WRAPPER_PATTERN.exec(token);
  const prefix = match?.[1] ?? "";
  const core = match?.[2] ?? token;
  const suffix = match?.[3] ?? "";
  if (core.length === 0) return token;
  if (core === "[redacted]") return token;

  if (SHELL_OPERATOR.test(core) || isSafeFlagName(core)) {
    return token;
  }

  // URL-shaped tokens get their own rendering (authority kept, path+query
  // tokenized/wholesale-redacted — see `classifyUrlToken`) rather than a
  // plain safe/unsafe boolean, so check this BEFORE the generic shape check.
  const urlRendering = classifyUrlToken(core, knownSafeTokens);
  if (urlRendering !== undefined) {
    return `${prefix}${urlRendering}${suffix}`;
  }

  if (isSafeValueShape(core, knownSafeTokens)) {
    return token;
  }

  const flagValueMatch = SAFE_FLAG_VALUE_PAIR.exec(core);
  // Round-10 CRITICAL fix (part b): the flag half used to be echoed back
  // unconditionally — a `--secretFlagName=value` where the FLAG half itself
  // glued a live secret next to a keyword would leak that half verbatim
  // regardless of the value half's own safety. The flag half must now pass
  // `isSafeFlagName` too; if it doesn't, the WHOLE token (not just the
  // value) falls through to the catch-all, exactly as if this branch had
  // never matched.
  if (flagValueMatch && isSafeFlagName(flagValueMatch[1] ?? "")) {
    const flag = flagValueMatch[1] ?? "";
    const value = flagValueMatch[2] ?? "";
    const valueUrlRendering = classifyUrlToken(value, knownSafeTokens);
    const safeValue =
      valueUrlRendering !== undefined
        ? valueUrlRendering
        : isSafeValueShape(value, knownSafeTokens)
          ? value
          : "[redacted]";
    return `${prefix}${flag}=${safeValue}${suffix}`;
  }

  return `${prefix}[redacted]${suffix}`;
}

/**
 * Sanitizes free text SOURCED FROM OUTSIDE this module — a hook-blocker's
 * recorded command/summary, a seed-failure reason, a daemon's recorded
 * reason/nextActions text, or any other caught-error message. Redacts by
 * default: only a token that is an exact member of `knownSafeTokens`, a flag
 * name, an ISO timestamp, a UUID, a path whose every segment passes the same
 * bounded checks, or a URL whose every path/query token passes them, survives
 * (round-8 terminal design — see the module header). A bare number no longer
 * survives by shape alone.
 *
 * `knownSafeTokens` defaults to an EMPTY set — a caller that doesn't supply a
 * vocabulary gets the strictest possible behavior, never a silent fallback
 * to shape-only trust.
 *
 * Do NOT call this on values the diagnosis layer generated itself (task ids,
 * run ids, role names, counts, its own recommended commands) — those are
 * structured, not free text, and should pass through `structured()` in
 * why-diagnosis.ts's `buildEvidence` instead.
 */
export function sanitizeFreeText(
  text: string,
  knownSafeTokens: ReadonlySet<string> = EMPTY_VOCABULARY
): string {
  const marked = applySecretMarkerRules(text, knownSafeTokens);
  return marked
    .split(/(\s+)/)
    .map((piece) => (/^\s+$/.test(piece) || piece.length === 0 ? piece : classifyToken(piece, knownSafeTokens)))
    .join("");
}

/** Truncates text to a safe display prefix, with an explicit ellipsis marker
 * when truncation occurred (never silently drops characters unmarked). */
export function truncateForDisplay(text: string, maxLength = MAX_COMMAND_DISPLAY_LENGTH): string {
  if (text.length <= maxLength) return text;
  return `${text.slice(0, maxLength)}…`;
}

/** Applies redaction then truncation — order matters: truncating first could
 * cut a token in half and hide it from the allowlist classifier, or worse,
 * cut a stage-1 marker match in half and leave a fragment of a secret
 * dangling past the truncation boundary. Redacting first guarantees nothing
 * unsafe survives regardless of where the truncation cut falls. */
export function sanitizeForDisplay(
  text: string,
  knownSafeTokens: ReadonlySet<string> = EMPTY_VOCABULARY
): string {
  return truncateForDisplay(sanitizeFreeText(text, knownSafeTokens));
}
