/**
 * App — Archon Forge Swimlane Monitor (Phase 0, Direction C).
 *
 * Renders the read-only run status dashboard by fetching a static JSON
 * snapshot from /snapshot.json (generated by src/forge/snapshot.ts).
 *
 * States handled: loading, error, success.
 * Phase 1: swap fetchDashboardSnapshot for a live SSE or polling endpoint.
 */

import { useEffect, useState } from "react";
import { fetchDashboardSnapshot } from "./data/snapshot.ts";
import type { DashboardViewModel } from "./types/dashboard.ts";
import { Sidebar } from "./components/Sidebar.tsx";
import { RunHeader } from "./components/RunHeader.tsx";
import { BlockerStrip } from "./components/BlockerStrip.tsx";
import { GateSwimlane } from "./components/GateSwimlane.tsx";

type LoadState =
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "success"; data: DashboardViewModel };

function LoadingPanel() {
  return (
    <div className="state-panel" aria-live="polite" aria-label="Loading dashboard">
      <div className="state-panel__spinner" aria-hidden="true" />
      <span>Loading snapshot…</span>
    </div>
  );
}

function ErrorPanel({ message }: { message: string }) {
  return (
    <div className="state-panel" role="alert" aria-label="Dashboard error">
      <span className="state-panel__error-label">Error</span>
      <p className="state-panel__code">{message}</p>
    </div>
  );
}

function Dashboard({ data }: { data: DashboardViewModel }) {
  return (
    <div className="app-layout">
      {/* Sidebar: archon mark, run list, views */}
      <Sidebar currentRun={data.header} />

      {/* Main content area */}
      <main className="main">
        {/* Topbar: run title, runId, status, authority badge, pulse, snapshot age */}
        <RunHeader header={data.header} pulse={data.pulse} generatedAt={data.generatedAt} />

        {/* HERO: blocker strip — always rendered, dominant when blockers exist */}
        <BlockerStrip blockers={data.blockers} />

        {/* Swimlane grid: reviewer | security_reviewer | qa_engineer */}
        <GateSwimlane
          taskQueue={data.taskQueue}
          reviewGates={data.reviewGates}
        />
      </main>
    </div>
  );
}

export default function App() {
  const [state, setState] = useState<LoadState>({ status: "loading" });

  useEffect(() => {
    let cancelled = false;

    fetchDashboardSnapshot()
      .then((data) => {
        if (!cancelled) {
          setState({ status: "success", data });
        }
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          const message =
            err instanceof Error ? err.message : "Unknown error loading snapshot";
          setState({ status: "error", message });
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);

  if (state.status === "loading") {
    return <LoadingPanel />;
  }

  if (state.status === "error") {
    return <ErrorPanel message={state.message} />;
  }

  return <Dashboard data={state.data} />;
}
